### ISSUE TITLE
Programmatically Add HTML5 validation

### ISSUE THREAD

**Issue by bkkrishna** [tws-inc/ckeditor-html5-form-validation#1]
Hello there, 

I was wondering if you could elaborate how we could integrate this plugin within a PHP Framework (like Laravel) and programmatically (eg. using jQuery) add its validator. I have added this to my CKEditor but could not find any documentation on how we can activate its validator (such as required fields) programmatically.

**Comment by alexattws** [comment]
Well, you can have your PHP code on the server side parse the HTML produced by CKEditor and extract the HTML5 validation attribute values from the input tags.  You can then use the validation attribute values to do your validation.  Server side validation of input data gathered by forms created by CKEditor is outside the scope of CKEditor and this plugin for obvious reasons.

**Comment by alexattws** [comment]
Oh, one more thing.  HTML5 validation is performed on the client side by the browser that support HTML5 validation features (see http://caniuse.com/#feat=form-validation).  Also, you can use HTML5 validation JS libraries to do the validation on the client side (in case the browser doesn't support some of these features).

**Comment by bkkrishna** [comment]
Sorry that I could not make myself clear. Actually, I was asking if there is any implementation of this add on that helps us to do client-side validation (similar to HTML5's _required_ tag). Specifically, I was trying to use this add-on to do validation like the HTML5's required tag programmatically (which you can set from the CKeditor Form Builder UI) in the CKEditor for just textarea.
Would be more than thankful if you could provide me any solution regarding this kind of implementation.

**Comment by alexattws** [comment]
I have no idea, maybe this? https://github.com/ericelliott/h5Validate
