### ISSUE TITLE
German translation file

### ISSUE THREAD

**Issue by s1738berger** [tws-inc/ckeditor-html5-form-validation#2]
well, it is what it promisees to be...

[de.js.zip](https://github.com/tws-inc/ckeditor-html5-form-validation/files/915843/de.js.zip)

**Comment by alexattws** [comment]
Do you want to create a pull request for this?  Normally, this is how it works on GitHub.

**Comment by alexattws** [comment]
Thanks!

**Comment by alexattws** [comment]
BTW, @s1738berger, does this plugin function ok on CKEditor 4.6 and 4.5?  I haven't been testing it myself for a while.
